# Site settings
title: David Lord
email: david.lord@uqconnect.edu.au
description: > # this means to ignore newlines until "baseurl:"
  I'm interested in things.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "blog.lord.geek.nz" # the base hostname & protocol for your site
permalink: pretty
twitter_username: dal_geek
github_username:  d-lord
facebook_username: lord.david

# Build settings
markdown: kramdown

kramdown:
    math_engine: mathjax

# other
highlighter: pygments
