# Site settings
title: David Lord
email: david.lord@uqconnect.edu.au
description: > # this means to ignore newlines until "baseurl:"
  A geek's gossip column.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "d-lord.github.io" # the base hostname & protocol for your site
#twitter_username: jekyllrb
github_username:  d-lord
facebook_username: lord.david

# Build settings
markdown: kramdown

kramdown:
    math_engine: mathjax

# other
highlighter: pygments
